import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'IT' | 'EN';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  IT: {
    'nav.projects': 'Progetti',
    'nav.services': 'Servizi',
    'nav.ailab': 'AI.THRA LAB',
    'nav.news': 'Ultime Notizie',
    'nav.about': 'Chi Siamo',
    'nav.careers': 'Carriere',
    'nav.contact': 'Contatti',
    'nav.menu': 'Menu',
    'nav.close': 'Chiudi',
    'projects.title': 'OPERE SELEZIONATE',
    'projects.subtitle': 'ECCELLENZA INTEGRATA',
    'projects.selected': 'Portfolio',
    'projects.viewAll': 'Vedi Tutti i Progetti',
    'project.gardone.title': 'Grand Hotel Gardone',
    'project.gardone.location': 'Gardone Riviera (BS)',
    'project.gardone.category': 'PM & Construction Management',
    'project.gardone.services': 'Project Management, Construction Management',
    'project.gardone.duration': 'Dicembre 2025 — In corso',
    'project.gardone.value': '€8M (Lotto 1 & 2)',
    'project.gardone.desc': 'Una trasformazione visionaria per lo storico Grand Hotel Gardone, che segna il debutto italiano di LXR Hotels & Resorts (Hilton). AITHRA coordina il primo e secondo lotto (circa 10.000 mq) per Racco Spa, guidando la riqualificazione verso l’apertura prevista per il 2027.',
    'project.gardone.challenge': 'La complessità risiede nel bilanciare la preservazione del patrimonio architettonico con la necessità di infrastrutture moderne ad alte prestazioni. Coordinare demolizioni su larga scala pianificando al contempo costruzioni a secco avanzate per standard di ospitalità di lusso richiede una sequenza precisa.',
    'project.gardone.solution': 'Come Project e Construction Manager, implementiamo sistemi di controllo integrati per monitorare ogni fase di demolizione e ricostruzione. Il nostro approccio garantisce il mantenimento dell\'integrità strutturale mentre i nuovi layout interni soddisfano i moderni requisiti acustici e termici attraverso sistemi avanzati di cartongesso.',
    'project.gardone.outcome': 'Il progetto è attualmente in corso, con i primi lotti di demolizione e partizioni interne che procedono secondo il programma tecnico. Stiamo garantendo una transizione fluida dal guscio strutturale alle fasi di finitura di alto livello.',
    'project.quilico.title': 'Ex Asilo Quilico & Museo D’andrade',
    'project.quilico.location': 'Pavone Canavese (TO)',
    'project.quilico.category': 'Energia & GSE',
    'project.quilico.services': 'Diagnosi Energetica, Servizi EGE, Gestione GSE',
    'project.quilico.duration': 'Aprile 2026 — In corso',
    'project.quilico.desc': 'Un progetto di transizione energetica completo per lo storico ex Asilo Quilico e il Museo D\'andrade. Questo progetto esemplifica la nostra capacità di integrare la conformità normativa con l\'ingegneria tecnica di alto livello.',
    'project.quilico.challenge': 'Gli edifici storici presentano spesso vincoli strutturali significativi per i miglioramenti energetici. L\'obiettivo è ottenere lo stato di riqualificazione profonda navigando nel complesso panorama normativo italiano per la conservazione storica e gli incentivi pubblici.',
    'project.quilico.solution': 'Abbiamo impiegato Esperti in Gestione dell\'Energia (EGE) certificati per condurre una rigorosa diagnosi pre-intervento (UNI CEI EN 16247). Questo approccio basato sui dati ci ha permesso di selezionare gli interventi tecnici più efficienti, che abbiamo poi tradotto in una strategia completa di gestione del \'Portaltermico\' GSE.',
    'project.quilico.outcome': 'Integrando la diagnosi tecnica con la strategia amministrativa, stiamo garantendo i massimi incentivi per il comune, assicurando al contempo un salto di classe energetica post-intervento che riduce significativamente i costi operativi e l\'impronta di CO2.',
    'project.monza.title': 'Cascina San Giuseppe',
    'project.monza.location': 'Monza (MB)',
    'project.monza.category': 'Restauro & Strutture',
    'project.monza.services': 'Architettura, Ingegneria Strutturale, Sicurezza, Gestione Amianto',
    'project.monza.duration': 'Aprile 2026 — In corso',
    'project.monza.desc': 'Presso Cascina San Giuseppe a Monza, AITHRA sta gestendo il restauro di un complesso storico dei primi del \'900, concentrandosi sulla stabilità strutturale e sulla bonifica di materiali pericolosi.',
    'project.monza.challenge': 'L\'edificio soffriva di un degrado avanzato delle strutture del tetto in legno e della muratura. La presenza di amianto ha richiesto un protocollo di sicurezza di alto standard e una gestione ambientale integrata.',
    'project.monza.solution': 'Abbiamo fornito un servizio di ingegneria a ciclo completo: dal rilievo 3D e studio di fattibilità alla progettazione strutturale finale per il rinforzo del tetto e il consolidamento della muratura. Il nostro coordinamento della sicurezza garantisce la protezione dei residenti e dei lavoratori durante la delicata fase di rimozione dell\'amianto.',
    'project.monza.outcome': 'Il progetto preserva il carattere storico della facciata pur offrendo una struttura del tetto sicura e moderna. La nostra assistenza tecnico-amministrativa ha snellito il processo dei permessi, consentendo un inizio immediato dei lavori.',
    'project.label.client': 'Cliente',
    'project.label.area': 'Area',
    'project.label.duration': 'Durata',
    'project.label.value': 'Importo',
    'project.heading.challenge': 'La Sfida',
    'project.heading.solution': 'La Nostra Soluzione',
    'project.heading.outcome': 'Il Risultato',
    'project.heading.services': 'Servizi Offerti',
    'project.heading.technical': 'Focus Tecnico',
    'project.technical.desc': 'Implementazione di workflow BIM integrati e controllo dei costi guidato dall\'AI per garantire la massima efficienza in riqualificazioni su larga scala.',
    'project.button.enquire': 'Richiedi informazioni',
    'project.next': 'PROSSIMO PROGETTO',
    'project.viewCase': 'Vedi il caso studio completo',
    'project.back': 'INDIETRO',
    'projects.filter.year': 'ANNO',
    'projects.filter.type': 'TIPOLOGIA',
    'projects.filter.area': 'AREA INTERVENTO',
    'projects.filter.country': 'NAZIONE',
    'projects.filter.amount': 'IMPORTO',
    'projects.filter.services': 'SERVIZI',
    'filter.area.range1': '< 500 mq',
    'filter.area.range2': '500 - 2000 mq',
    'filter.area.range3': '2000 - 5000 mq',
    'filter.area.range4': '> 5000 mq',
    'filter.amount.range1': '< €500k',
    'filter.amount.range2': '€500k - €2M',
    'filter.amount.range3': '€2M - €10M',
    'filter.amount.range4': '> €10M',
    'filter.country.italy': 'Italia',
    'filter.country.usa': 'USA',
    'filter.country.france': 'Francia',
    'filter.country.germany': 'Germania',
    'filter.country.uk': 'Regno Unito',
    'filter.country.spain': 'Spagna',
    'filter.country.switzerland': 'Svizzera',
    'filter.country.uae': 'Emirati Arabi',
    'filter.all': 'Tutti',
    'filter.type.hospitality': 'Ospitalità',
    'filter.type.public': 'Pubblico',
    'filter.type.residential': 'Residenziale',
    'filter.category.pm': 'PM & Construction Management',
    'filter.category.energy': 'Energia & GSE',
    'filter.category.restoration': 'Restauro & Strutture',
    'filter.service.pm': 'Project Management',
    'filter.service.construction': 'Construction Management',
    'filter.service.energy': 'Energia',
    'filter.service.gse': 'GSE',
    'filter.service.architecture': 'Architettura',
    'filter.service.structures': 'Strutture',
    'projects.noResults': 'Nessun progetto corrisponde ai filtri selezionati.',
    'ai.tag': 'Innovation Hub',
    'ai.title': 'AI.THRA LAB',
    'ai.desc': "L'intelligenza artificiale al servizio del progetto: algoritmi proprietari per l'ottimizzazione strutturale, simulazione energetica e design generativo.",
    'ai.heads.title': 'RESPONSABILI DELL\'AREA',
    'ai.heads.01.name': 'CIRIACO ALBERTO BELMONTE',
    'ai.heads.01.role': 'Head of AI',
    'ai.heads.01.bio': 'Guida la visione strategica dell\'AI Lab, supervisionando lo sviluppo di modelli di calcolo avanzati e l\'integrazione di tecnologie proprietarie.',
    'ai.heads.02.name': 'SIMONE MIRAGLIA',
    'ai.heads.02.role': 'AI & BIM Strategy Manager',
    'ai.heads.02.bio': 'Gestisce l\'operatività dei reparti AI e BIM, assicurando una transizione digitale fluida e l\'ottimizzazione dei flussi di lavoro.',
    'ai.publications.title': 'PUBBLICAZIONI',
    'ai.publications.01.title': 'projetando possibilidades conferéncia ubiqua',
    'ai.publications.01.journal': 'SIGRADI 2021 — Strategie Parametriche in un Laboratorio di Progettazione Architettonica, pp 511-522',
    'ai.publications.01.year': '2021',
    'ai.projects.title': 'OUR PROJECTS',
    'ai.projects.01.title': 'ENERGY TWIN 3D',
    'ai.projects.01.type': 'Virtual EGE',
    'ai.projects.01.desc': 'Simulazioni energetiche real-time in ambiente 3D. Un\'intelligenza artificiale addestrata per dialogare con il cliente e ottimizzare le prestazioni globali dell\'edificio.',
    'ai.projects.01.status': 'In Produzione',
    'ai.projects.02.title': 'AITHRA OMNIA',
    'ai.projects.02.type': 'Process Bot',
    'ai.projects.02.desc': 'Gestione integrale dell\'infrastruttura: controllo qualità, monitoraggio processi e supporto proattivo in cantiere. Riduzione dell\'errore stimata al 3%.',
    'ai.projects.02.status': 'Active Sentinel',
    'ai.projects.03.title': 'URBANISTICA AI',
    'ai.projects.03.type': 'Regulatory Bot',
    'ai.projects.03.desc': 'Supporto normativo in tempo reale. Bot addestrati sulla legislazione urbanistica italiana per garantire conformità totale durante ogni fase progettuale.',
    'ai.projects.03.status': 'Safe Check',
    'ai.athena.title': 'ATHENA 1',
    'ai.athena.subtitle': 'PROPRIETARY AI ENGINE',
    'ai.athena.desc': 'Il nostro software proprietario per l\'ottimizzazione strutturale e la simulazione energetica in tempo reale.',
    'ai.athena.status': 'SISTEMA OPERATIVO',
    'ai.athena.version': 'VERSIONE 1.4.2',
    'about.title': 'CHI SIAMO',
    'about.subtitle': 'L\'ECCELLENZA NELL\'INGEGNERIA INTEGRATA',
    'about.desc': "Da oltre 25 anni di esperienza ingegneristica combinata a un'azienda innovativa guidata dall'IA. AITHRA riunisce un team multidisciplinare di professionisti con background diversi in design, ingegneria e tecnologia, uniti da un approccio condiviso e una visione comune.\n\nSviluppiamo soluzioni integrate in cui architettura, ingegneria e intelligenza artificiale convergono per creare edifici capaci di gestire l'energia in modo predittivo, efficiente e adattivo.\n\nIl nostro lavoro è radicato nell'esperienza, ma orientato all'innovazione: ogni progetto è concepito come un sistema, in cui competenze tecniche, controllo dei processi e strumenti avanzati operano insieme per fornire risultati ad alte prestazioni, resilienti e lungimiranti.",
    'about.headline.main': '25 ANNI DI',
    'about.headline.sub': 'ECCELLENZA',
    'about.philosophy.title': 'LA NOSTRA EVOLUZIONE',
    'about.philosophy.text': 'AITHRA nasce dall\'unione di venticinque anni di esperienza nel settore delle costruzioni con le più avanzate tecnologie di Intelligenza Artificiale.',
    'about.integrated.title': 'MISSIONE',
    'about.integrated.desc': 'Democratizzare l\'innovazione per accelerare la transizione energetica e supportare i criteri ESG.',
    'about.sustainable.title': 'VALORI',
    'about.sustainable.desc': 'Eccellenza tecnica, sostenibilità integrata e innovazione responsabile guidano ogni nostro progetto.',
    'about.experience.label': 'Esperienza',
    'about.experience.value': '25+ Anni',
    'about.people': 'IL NOSTRO TEAM',
    'about.people.subtitle': 'BOARD',
    'about.people.desc': 'Un team di tecnici e ricercatori dedicati alla trasformazione digitale del settore.',
    'about.team.fullDesc': 'Il nostro studio è un ecosistema di creatività e collaborazione. Uno spazio dove ogni membro del team contribuisce attivamente all\'innovazione, lavorando in un ambiente dinamico e stimolante che favorisce il benessere e lo scambio continuo di conoscenze.',
    'about.team.member.01.name': 'Ciriaco Alberto Belmonte',
    'about.team.member.01.role': 'CEO e AI Research Lead',
    'about.team.member.01.degree': 'Ingegnere Civile (Idraulica)',
    'about.team.member.02.name': 'Pierluigi Bisogno',
    'about.team.member.02.role': 'Technical Director and Head of Proposal',
    'about.team.member.02.degree': 'Ingegnere Civile',
    'about.team.member.03.name': 'Francesco Nepita',
    'about.team.member.03.role': 'Production and Construction Manager',
    'about.team.member.03.degree': 'Ingegnere Edile',
    'about.team.employee.01.name': 'Simone Miraglia',
    'about.team.employee.01.role': 'Bid manager and head of Architecture',
    'about.team.employee.01.degree': 'Ingegnere Edile (Architettura)',
    'about.team.employee.02.name': 'Daniele Chiriaco',
    'about.team.employee.02.role': 'Project and construction manager',
    'about.team.employee.02.degree': 'Ingegnere Edile',
    'about.team.employee.03.name': 'Brighten Joseph',
    'about.team.employee.03.role': 'MEP & Energy Design Engineer',
    'about.team.employee.03.degree': 'Ingegnere Meccanico (Sistemi di Controllo)',
    'about.team.employee.04.name': 'William Koerner',
    'about.team.employee.04.role': 'Architetto Senior',
    'about.team.employee.04.degree': 'Architetto Ambientale',
    'about.presence.title': 'LA NOSTRA PRESENZA',
    'about.map.title': 'LE NOSTRE SEDI',
    'about.map.milan': 'MILANO — VIALE COL DI LANA 8',
    'about.location.01.type': 'Headquarters',
    'about.location.02.type': 'Design Studio',
    'about.location.03.type': 'Innovation Hub',
    'about.location.04.type': 'Regional Office',
    'careers.title': 'CARRIERE',
    'careers.subtitle': 'UNISCITI AL NOSTRO TEAM',
    'careers.desc': 'Siamo sempre alla ricerca di talenti appassionati di innovazione e sostenibilità.',
    'careers.headline.main': 'COSTRUISCI',
    'careers.headline.sub': 'LA TUA CARRIERA',
    'careers.job.01.title': 'Responsabile Amministrativo',
    'careers.job.01.type': 'Contenabilità e Fatturazione',
    'careers.job.01.desc': 'Ricerchiamo una figura per la gestione integrale dei processi amministrativi. La risorsa si occuperà della fatturazione attiva/passiva, gestione dei flussi finanziari su piattaforma Odoo, coordinamento con i consulenti contabili e supporto nella redazione di contratti e documenti societari. È richiesta un\'ottima conoscenza della lingua inglese.',
    'careers.job.01.skills': 'Gestione amministrativa, contabilità base, amministrazione del personale, inglese fluente.',
    'careers.job.01.software': 'Odoo ERP, Pacchetto Office (Excel avanzato), Portali di fatturazione elettronica.',
    'careers.job.02.title': 'BIM Coordinator',
    'careers.job.02.type': 'Progettazione Integrata',
    'careers.job.02.desc': 'Selezioniamo un BIM Coordinator con esperienza in progetti multidisciplinari complessi. La figura sarà responsabile dell\'implementazione dei processi BIM, gestione delle interferenze (Clash Detection), sviluppo di standard informativi e ottimizzazione dei flussi di lavoro. È richiesta l\'ottima conoscenza della lingua inglese per il coordinamento con partner internazionali.',
    'careers.job.02.skills': 'BIM Management, Computational Design, Coordinamento Team, inglese fluente.',
    'careers.job.02.software': 'Autodesk Revit (Expert), Dynamo, Rhino + Grasshopper, Navisworks, BIM 360/ACC.',
    'careers.job.03.title': 'Junior Architect / Engineer',
    'careers.job.03.type': 'Tender Specialist',
    'careers.job.03.desc': 'La risorsa supporterà l\'ufficio gare nella preparazione di offerte tecniche per appalti nazionali e internazionali. Il ruolo prevede l\'analisi critica dei documenti di bando, la redazione di relazioni tecniche metodologiche in italiano e inglese e il coordinamento con i partner di raggruppamento.',
    'careers.job.03.skills': 'Analisi bandi di gara, redazione tecnica, inglese professionale, pianificazione processi.',
    'careers.job.03.software': 'Pacchetto Office, Adobe Creative Suite (InDesign/Photoshop), Software di Project Management.',
    'careers.job.04.title': 'Junior Architect / Engineer',
    'careers.job.04.type': 'Energy Diagnosis specialist',
    'careers.job.04.desc': 'Cerchiamo un profilo junior focalizzato sull\'analisi energetica e la sostenibilità applicata agli edifici esistenti. La figura si occuperà di rilievi tecnici, modellazione energetica e simulazioni termiche. La conoscenza dell\'inglese è fondamentale per la ricerca e lo sviluppo di modelli predittivi con il team AI.',
    'careers.job.04.skills': 'Diagnosi energetiche, Termotecnica, Modellazione energetica, inglese professionale.',
    'careers.job.04.software': 'ACCA Termus, Autodesk Revit, Software di simulazione dinamica, Excel.',
    'careers.job.05.title': 'Senior MEP Engineer',
    'careers.job.05.type': 'Progettazione Impianti',
    'careers.job.05.desc': 'Ricerchiamo un Ingegnere Impiantista (MEP) con consolidata esperienza nella progettazione di sistemi complessi. La figura dovrà gestire i progetti in totale autonomia, dal concept alla fase esecutiva, assicurando l\'integrazione con le altre discipline e il rispetto degli standard di efficienza energetica. È richiesta la fluidità nella lingua inglese.',
    'careers.job.05.skills': 'Progettazione MEP, Autonomia gestionale, Coordinamento multidisciplinare, inglese fluente.',
    'careers.job.05.software': 'Autodesk Revit, MagiCAD, Software di calcolo termotecnico ed elettrico.',
    'careers.apply': 'CANDIDATI ORA',
    'careers.requirements': 'REQUISITI',
    'careers.software': 'SOFTWARE RICHIESTI',
    'careers.spontaneous.title': 'CANDIDATURA SPONTANEA',
    'careers.spontaneous.desc': 'Non trovi la posizione giusta? Inviaci il tuo CV e raccontaci come puoi fare la differenza.',
    'careers.culture.title': 'PIÙ DI UN LAVORO',
    'careers.culture.desc': 'In AITHRA non cerchiamo solo professionisti, ma sognatori pragmatici. Siamo persone smart, vivaci, e crediamo che la vera innovazione nasca dallo scambio libero di idee. Il nostro ambiente promuove la contaminazione di conoscenze e idee in maniera trasversale: qui ogni membro del team è incoraggiato a mettere in discussione lo status quo e a contribuire con la propria visione unica, in un clima di continua crescita collettiva.',
    'careers.culture.grid.1': 'CONTAMINAZIONE DI IDEE',
    'careers.culture.grid.2': 'TRASVERSALITÀ',
    'careers.culture.grid.3': 'AMBIENTE VIVACE',
    'contact.title': 'CONTATTI',
    'contact.subtitle': 'PARLIAMO DEL TUO PROGETTO',
    'contact.desc': 'Siamo pronti ad aiutarti a realizzare le tue sfide più ambiziose.',
    'contact.headline.main': 'METTITI IN',
    'contact.headline.sub': 'CONTATTO',
    'contact.details.title': 'DETTAGLI',
    'contact.details.inquiries': 'INFORMAZIONI',
    'contact.details.phone': 'TELEFONO',
    'contact.details.office': 'UFFICIO',
    'contact.form.title': 'INVIACI UN MESSAGGIO',
    'contact.form.name': 'NOME',
    'contact.form.email': 'EMAIL',
    'contact.form.subject': 'OGGETTO',
    'contact.form.message': 'MESSAGGIO',
    'contact.form.placeholder.name': 'Il tuo nome',
    'contact.form.placeholder.email': 'la tua email',
    'contact.form.placeholder.subject': 'Di cosa vuoi parlare?',
    'contact.form.placeholder.message': 'Scrivi qui il tuo messaggio...',
    'contact.form.send': 'INVIA MESSAGGIO',
    'contact.faq.title': 'DOMANDE FREQUENTI',
    'contact.faq.subtitle': 'Risposte rapide alle domande più comuni',
    'contact.faq.01.q': 'Quanto costa una consulenza iniziale?',
    'contact.faq.01.a': 'La prima consulenza conoscitiva è gratuita e senza impegno. Durante l\'incontro analizziamo le tue esigenze e ti proponiamo un percorso personalizzato con preventivo dettagliato.',
    'contact.faq.02.q': 'In quanto tempo ricevo una risposta?',
    'contact.faq.02.a': 'Il nostro team risponde a tutte le richieste entro 24 ore lavorative. Per urgenze puoi contattarci direttamente al numero telefonico indicato.',
    'contact.faq.03.q': 'Operate anche fuori Milano?',
    'contact.faq.03.a': 'Sì, operiamo su tutto il territorio nazionale. Abbiamo gestito progetti in Lombardia, Veneto, Emilia-Romagna, Piemonte e altre regioni italiane.',
    'contact.faq.04.q': 'Quali settori seguite?',
    'contact.faq.04.a': 'Lavoriamo con Pubbliche Amministrazioni, industria, terziario e residenziale. Abbiamo esperienza con ospedali, scuole, stabilimenti produttivi, catene retail, hotel e condomini.',
    'contact.faq.05.q': 'Gestite anche le pratiche per gli incentivi?',
    'contact.faq.05.a': 'Assolutamente sì. Ci occupiamo di tutte le pratiche: Certificati Bianchi, Conto Termico 3.0, Piano Transizione 5.0, bandi PNRR e fondi regionali.',
    'home.hero.title': 'Progettiamo un futuro',
    'home.hero.subtitle': 'sostenibile e green',
    'home.hero.tagline': 'AITHRA: FORMA. SISTEMA . ENERGIA.',
    'home.hero.description': 'Uniamo architettura, ingegneria e intelligenza dei processi in un nuovo modo di progettare.',
    'home.hero.engineering': 'Engineering Excellence',
    'home.integrated.tag': 'Progettazione Integrata',
    'home.approach.tag': 'Il Nostro Approccio',
    'home.approach.title': 'PROGETTAZIONE INTEGRATA E TECNOLOGIA',
    'home.approach.desc': 'Il nostro metodo si basa sulla fusione tra creatività umana e precisione parametrica. Ogni progetto è un ecosistema dove architettura, ingegneria e sostenibilità coesistono in perfetta armonia.',
    'home.expertise.tag': 'La Nostra Esperienza',
    'home.expertise.title': 'ECCELLENZA IN OGNI DISCIPLINA',
    'home.expertise.desc': 'Dalla progettazione integrata alla gestione BIM avanzata, offriamo soluzioni complete per le sfide più ambiziose del settore delle costruzioni.',
    'home.news.tag': 'News & Insights',
    'home.news.title': 'ULTIME NOVITÀ',
    'home.news.item1.title': 'CONTO TERMICO 3.0',
    'home.news.item1.desc': 'Scopri le nuove opportunità per l\'efficienza energetica e come accedere ai nuovi incentivi 2026.',
    'home.news.item2.title': 'AI NELLA PROGETTAZIONE',
    'home.news.item2.desc': 'Come l\'intelligenza artificiale sta rivoluzionando la progettazione e la sostenibilità degli edifici.',
    'home.news.item3.title': 'SMART TOOLS CON AI',
    'home.news.item3.desc': 'Strumenti avanzati per la progettazione integrata e l\'ottimizzazione dei processi.',
    'home.news.item4.title': 'TRANSIZIONE ENERGETICA',
    'home.news.item4.desc': 'Strategie e soluzioni per un futuro a zero emissioni e l\'indipendenza energetica.',
    'news.conto-termico.content': `Il Conto Termico 3.0, introdotto per il 2026, rappresenta una pietra miliare nella strategia nazionale per la decarbonizzazione del parco immobiliare. Questa normativa potenzia significativamente gli incentivi per la sostituzione di impianti di climatizzazione invernale con sistemi ad alta efficienza.

Punti chiave del nuovo regime:
- Maggiori incentivi per pompe di calore aria-acqua e geotermiche, con coperture fino al 65% della spesa sostenuta.
- Inclusione di sistemi ibridi avanzati e integrazione con il solare termico per la produzione di acqua calda sanitaria.
- Semplificazione delle procedure di accesso tramite portali digitali integrati, riducendo i tempi di istruttoria.

Il team di AITHRA supporta i clienti in ogni fase: dalla diagnosi energetica preliminare alla progettazione degli impianti, fino alla gestione completa delle pratiche amministrative per garantire il massimo ritorno sull'investimento.`,
    'news.ai-engineering.content': `L'integrazione dell'intelligenza artificiale nei processi di ingegneria non è più un'opzione, ma una necessità per gestire la complessità dei moderni progetti edilizi. AITHRA utilizza algoritmi proprietari per trasformare i dati in decisioni progettuali ottimizzate.

Applicazioni pratiche:
- Ottimizzazione Strutturale: Riduzione dell'uso di materiali (acciaio e calcestruzzo) attraverso algoritmi generativi che mantengono standard di sicurezza superiori.
- Simulazioni Energetiche: Utilizzo di modelli predittivi per analizzare il comportamento dell'edificio nelle diverse condizioni climatiche stagionali.
- Generative Design: Esplorazione automatizzata di migliaia di opzioni spaziali per ottimizzare luce naturale, ventilazione e comfort acustico.

Questo approccio permette a progettisti e committenti di visualizzare le performance dell'opera prima ancora dell'inizio del cantiere, minimizzando rischi e costi imprevisti.`,
    'news.smart-tools.content': `I nuovi Smart Tools sviluppati da AITHRA sono progettati per colmare il divario tra la progettazione ufficio e l'esecuzione in cantiere. Attraverso l'uso dell'AI, questi strumenti consentono una gestione proattiva e intelligente di tutte le fasi realizzative.

Le funzionalità principali includono:
- Digital Twin in tempo reale: Modelli 3D interattivi che si aggiornano costantemente riflettendo l'andamento reale dei lavori.
- Controllo Qualità Automatizzato: Sistemi di computer vision che rilevano discrepanze tra il modello BIM e l'opera realizzata, segnalando potenziali clash.
- Gestione della Sicurezza: Algoritmi che monitorano l'ambiente di lavoro per prevenire situazioni di rischio per le maestranze.

L'adozione di questi strumenti porta a una riduzione drastica degli sprechi di materiale e a un rispetto rigoroso dei cronoprogrammi stabiliti.`,
    'news.energy-transition.content': `La transizione energetica è la sfida principale del nostro secolo per il settore delle costruzioni. Le nuove normative europee, incluse le direttive EPBD (Energy Performance of Buildings Directive), impongono standard sempre più severi per il risparmio energetico e la sostenibilità.

Le strategie di AITHRA per il futuro:
- Decarbonizzazione degli Edifici: Sostituzione delle fonti fossili con energie rinnovabili integrate direttamente nell'architettura.
- Comunità Energetiche Rinnovabili (CER): Progettazione di sistemi che permettono la condivisione dell'energia tra edifici vicini, massimizzando l'autoconsumo.
- Analisi del Ciclo di Vita (LCA): Valutazione dell'impatto ambientale di ogni componente edilizio, dalla produzione allo smaltimento.

Investire oggi nella sostenibilità significa non solo proteggere il pianeta, ma anche garantire il valore immobiliare degli asset nel lungo periodo, anticipando le richieste di un mercato sempre più attento ai criteri ESG.`,
    'news.milan-arch-week.content': `Milano Arch Week è la manifestazione di riferimento dedicata all'architettura, all'urbanistica e al futuro delle città, promossa dal Comune di Milano, dal Politecnico di Milano e da Triennale Milano. L'evento trasforma la città in un laboratorio a cielo aperto per riflettere sulle grandi trasformazioni urbane contemporanee.

La gestione della manifestazione prevede un coordinamento corale tra istituzioni accademiche e culturali, proponendo un palinsesto che spazia da lecture di architetti di fama internazionale a workshop operativi, tour guidati e dibattiti aperti alla cittadinanza. 

Il focus dell'edizione 2026 si concentra sulla "Città Prossima", analizzando come la tecnologia, il verde urbano e le nuove forme di mobilità possano integrarsi per creare ecosistemi cittadini più resilienti e inclusivi.`,
    'news.aithra-genesis.content': `Il nome AITHRA deriva dal termine greco αἰθήρ (aithḗr), che indica l’etere: l’aria più pura, il cielo limpido, ciò che è invisibile ma essenziale. Un concetto che richiama trasparenza, leggerezza ed energia, e che rappresenta in modo coerente il ruolo che oggi le tecnologie intelligenti possono assumere nei processi complessi.

AITHRA è una start-up innovativa che sviluppa soluzioni integrate tra progettazione, ingegneria e intelligenza artificiale, con l’obiettivo di rendere i sistemi più efficienti, controllabili e sostenibili. L’innovazione non è trattata come un elemento separato, ma come parte strutturale del metodo, capace di operare in modo discreto ma determinante all’interno dei processi.

La società nasce dall’incontro tra professionisti che condividono un percorso comune e oltre venticinque anni di esperienza complessiva nel settore. Un gruppo che ha scelto di unire competenze complementari — progettuali, tecniche e organizzative — per costruire un modello operativo più integrato.

AITHRA si propone come interlocutore unico per clienti pubblici e privati, accompagnando ogni intervento lungo tutte le sue fasi: dall’analisi preliminare alla progettazione, dal coordinamento alla realizzazione. Un approccio che consente di mantenere continuità, controllo e coerenza lungo l’intero sviluppo del progetto.

Alla base c’è una visione chiara: strutturare un processo in cui le diverse competenze dialogano in modo sistemico, supportate da strumenti avanzati e da un’organizzazione in grado di governare la complessità senza disperderla.

AITHRA è, quindi, un sistema costruito per dare forma a progetti più consapevoli, in cui tecnologia, metodo e progettazione operano insieme con precisione e continuità.`,
    'news.archive.title': 'ARCHIVIO NOTIZIE & PUBBLICAZIONI',
    'news.archive.subtitle': 'STORIE, PROGETTI E INTERVENTI',
    'news.filter.all': 'TUTTO',
    'news.filter.articles': 'ARTICOLI',
    'news.filter.publications': 'PUBBLICAZIONI',
    'news.filter.events': 'EVENTI',
    'news.filter.stories': 'STORIE',
    'services.title': 'I NOSTRI SERVIZI',
    'services.subtitle': 'SOLUZIONI INTEGRATE PER IL FUTURO DELLE COSTRUZIONI',
    'services.architettura.title': 'ARCHITETTURA',
    'services.architettura.desc': 'Progettazione architettonica integrata in ambiente BIM. Trasformiamo visioni in realtà attraverso un design funzionale, estetico e sostenibile.',
    'services.architettura.items': 'Concept Design, Progettazione Definitiva ed Esecutiva, Modellazione BIM Avanzata, Interior Design, Certificazioni LEED/BREEAM',
    'services.strutture.title': 'STRUTTURE',
    'services.strutture.desc': 'Soluzioni ingegneristiche all\'avanguardia per strutture complesse. Sicurezza, ottimizzazione dei materiali e precisione tecnica.',
    'services.strutture.items': 'Calcolo Strutturale NTC 2018, Progettazione Antisismica, Consolidamento Edilizio, Strutture in Acciaio e Cemento Armato, Analisi FEM',
    'services.impianti.title': 'IMPIANTI & MEP',
    'services.impianti.desc': 'Progettazione di sistemi impiantistici ad alta efficienza. Integrazione perfetta tra architettura e tecnologia per il massimo comfort.',
    'services.impianti.items': 'Impianti Termici ed Elettrici, Fotovoltaico e Rinnovabili, Building Automation (BACS), Sistemi HVAC, Antincendio',
    'services.ai.title': 'AI & DIGITAL TWIN',
    'services.ai.title2': 'DIGITAL TWIN',
    'services.ai.desc': 'Sviluppo di modelli digitali e algoritmi predittivi per l\'ottimizzazione delle performance energetiche e gestionali.',
    'services.ai.items': 'Algoritmi Predittivi Proprietari, Digital Twin Energetici, Piattaforma AITHRA SaaS, Integrazione IoT/BMS',
    'services.energia.title': 'SOSTENIBILITÀ & ENERGIA',
    'services.energia.desc': 'Consulenza strategica per la transizione energetica. Diagnosi, monitoraggio e accesso agli incentivi per un futuro Green.',
    'services.energia.items': 'Diagnosi Energetiche D.Lgs 102/2014, Consulenza ESG, Accesso Incentivi 2026, Comunità Energetiche (CER)',
    'services.cta.title': 'Il nostro approccio multidisciplinare ridefinisce i confini dell\'ingegneria.',
    'services.cta.tagline': 'Progettazione Integrata — Ottimizzazione IA — Futuro Sostenibile',
    'services.cta.button': 'Lavora con noi',
    'services.tender.title': 'TENDER',
    'services.tender.desc': 'Supporto tecnico e gestionale per gare d\'appalto pubbliche e private. Gestione completa della documentazione tecnica.',
    'services.tender.items': 'Gestione Appalti Pubblici, PNRR, Computi Metrici Estimativi, Supporto Tecnico Gare',
    'services.rilievo.title': 'RILIEVO & DIGITALIZZAZIONE',
    'services.rilievo.desc': 'Acquisizione digitale dello stato di fatto attraverso tecnologie di rilievo avanzate e precisione millimetrica.',
    'services.rilievo.items': 'Rilievi Laser Scanner 3D, Fotogrammetria, Restituzione BIM (Scan-to-BIM), Rilievi Architettonici',
    'footer.desc': 'AITHRA è una società di ingegneria e architettura all\'avanguardia, specializzata in soluzioni integrate e sostenibili.',
    'footer.navigation': 'NAVIGAZIONE',
    'footer.contact': 'CONTATTI',
    'footer.newsletter': 'NEWSLETTER',
    'footer.newsletter.desc': 'Iscriviti per ricevere aggiornamenti sui nostri progetti e innovazioni tecnologiche.',
    'footer.join': 'ISCRIVITI',
    'footer.allRights': '© 2026 AITHRA S.R.L. TUTTI I DIRITTI RISERVATI.',
    'footer.privacy': 'PRIVACY POLICY',
    'footer.terms': 'TERMINI E CONDIZIONI',
    'home.hero.intro.desc': 'Colmiamo il divario tra creatività umana e precisione computazionale. AITHRA fornisce soluzioni integrate in architettura, ingegneria strutturale, MEP, BIM e sostenibilità, potenziate dal nostro software proprietario EGE Virtuale, con oltre venticinque anni di esperienza nel settore.',
    'home.hero.intro.expertise': 'Competenze',
    'home.hero.intro.integrated': 'Progettazione Integrata & BIM',
    'home.hero.intro.sustainability': 'Sostenibilità Energetica',
    'home.hero.intro.construction': 'Gestione del Cantiere',
    'home.integrated.title': 'DESIGN INTEGRATO',
    'home.integrated.title.sub': 'INGEGNERIA DI SISTEMA',
    'home.integrated.quote': 'Forniamo una perfetta integrazione delle discipline, assicurando che ogni progetto sia ottimizzato per prestazioni, sostenibilità ed esperienza umana.',
    'home.integrated.desc': 'Il nostro approccio olistico assicura che architettura, ingegneria e strategia ambientale lavorino come un unico organismo ad alte prestazioni.',
    'home.integrated.link': 'Esplora i nostri servizi —>',
    'home.approach.step1.title': 'RICERCA',
    'home.approach.step1.desc': 'Analisi approfondita del contesto e dei vincoli.',
    'home.approach.step2.title': 'OTTIMIZZAZIONE',
    'home.approach.step2.desc': 'Raffinatezza algoritmica di ogni parametro.',
    'home.approach.step3.title': 'CONSEGNA PRECISA',
    'home.approach.step3.desc': 'Esecuzione meticolosa attraverso BIM e gestione intelligente dei processi.',
    'home.expertise.core.title': 'Focus Principale',
    'home.expertise.core.item1': 'Progettazione Multidisciplinare',
    'home.expertise.core.item2': 'Sostenibilità Energetica',
    'home.expertise.core.item3': 'Architettura Parametrica',
    'home.expertise.digital.title': 'Digital Twin',
    'home.expertise.digital.item1': 'BIM LOD 500',
    'home.expertise.digital.item2': 'Gestione Intelligente dei Beni',
    'home.expertise.digital.item3': 'Manutenzione Predittiva',
    'home.news.more': 'Leggi di più —>',
    'home.metric.title.1': 'Operiamo all\'',
    'home.metric.title.2': 'intersezione',
    'home.metric.title.3': 'tra intuizione e',
    'home.metric.title.4': 'precisione parametrica.',
    'home.metric.desc': 'AITHRA non è solo uno studio di ingegneria. Siamo un laboratorio dell\'ambiente costruito, dove ogni struttura è ottimizzata attraverso modelli di IA proprietari per raggiungere livelli senza precedenti di efficienza e armonia estetica.',
    'home.metric.label': 'Metrica Chiave',
    'home.metric.value.desc': 'Riduzione media dell\'impronta di carbonio strutturale in tutti i progetti del 2026.',
    'home.team.desc': 'Il nostro team è un ibrido di eccellenza ingegneristica e ricerca computazionale.',
    'home.cta.title.1': 'Costruiamo il',
    'home.cta.title.2': 'futuro insieme.',
    'home.cta.button': 'Inizia una Conversazione',
    'seo.home.title': 'AITHRA | Ingegneria Integrata, Architettura e AI',
    'seo.home.description': 'AITHRA unisce architettura, ingegneria e intelligenza artificiale per progettare un futuro sostenibile. Oltre 25 anni di esperienza in soluzioni ingegneristiche integrate.',
    'seo.projects.title': 'Progetti | Portfolio di Ingegneria e Architettura | AITHRA',
    'seo.projects.description': 'Esplora le opere selezionate di AITHRA: dal Grand Hotel Gardone alla riqualificazione energetica del Museo D’andrade. Eccellenza in PM e Construction Management.',
    'seo.services.title': 'Servizi | Ingegneria, Architettura e Sostenibilità | AITHRA',
    'seo.services.description': 'Soluzioni integrate: Architettura BIM, Calcolo Strutturale, Impianti MEP, Digital Twin e consulenza per la Transizione Energetica.',
    'seo.ailab.title': 'AI.THRA LAB | Innovazione e Intelligenza Artificiale | AITHRA',
    'seo.ailab.description': 'Il nostro Innovation Hub: algoritmi proprietari per l’ottimizzazione strutturale, simulazione energetica e design generativo applicato all’edilizia.',
    'seo.about.title': 'Chi Siamo | La Nostra Evoluzione e il Team | AITHRA',
    'seo.about.description': 'Scopri la storia di AITHRA, la missione e il team multidisciplinare guidato da CEO Ciriaco Alberto Belmonte. Tradizione tecnica e innovazione tecnologica.',
    'seo.careers.title': 'Carriere | Unisciti al Team AITHRA | Lavora con Noi',
    'seo.careers.description': 'Siamo alla ricerca di talenti: BIM Coordinator, Ingegneri MEP, specialisti in Diagnosi Energetica. Entra a far parte di un ambiente vivace e innovativo.',
    'seo.news.title': 'News e Pubblicazioni | Insights dal Mondo AITHRA',
    'seo.news.description': 'Resta aggiornato sul Conto Termico 3.0, l’IA nella progettazione e le ultime novità sulla transizione energetica e sostenibilità.',
    'seo.contact.title': 'Contatti | Parliamo del Tuo Progetto | AITHRA',
    'seo.contact.description': 'Contatta lo studio AITHRA a Milano. Richiedi una consulenza per ingegneria integrata, pratiche GSE o progettazione sostenibile.',
    'footer.transparency': 'OBBLIGHI DI TRASPARENZA',
    'transparency.title': 'OBBLIGHI DI TRASPARENZA',
    'transparency.headline.main': 'TRASPARENZA',
    'transparency.headline.sub': 'E PRIVACY',
    'transparency.desc': 'Quadro normativo e informativo relativo agli obblighi di pubblicità legale, trasparenza amministrativa e protocolli di data governance di AITHRA S.r.l.',
    'transparency.section.company.title': 'Dati Societari e Identificativi',
    'transparency.section.company.name': 'Ragione Sociale: AITHRA S.r.l.',
    'transparency.section.company.vat': 'P.IVA / C.F.: 14597360966',
    'transparency.section.company.address': 'Sede Legale: Viale Col di Lana 8, 20136 Milano (MI)',
    'transparency.section.insurance.title': 'Manleva e Copertura Assicurativa',
    'transparency.section.insurance.desc': 'AITHRA S.r.l. opera sotto copertura di polizza di Responsabilità Civile Professionale (All Risks), con massimali idonei alla complessità delle commesse e in piena conformità alle vigenti normative per le Società di Ingegneria.',
    'transparency.section.subsidies.title': 'Obblighi di Trasparenza - Contributi Pubblici',
    'transparency.section.subsidies.desc': 'Ai sensi della Legge 124/2017, si segnala che gli aiuti di Stato e gli aiuti de minimis percepiti dalla società sono consultabili nel Registro Nazionale degli Aiuti di Stato (RNA), in ottemperanza agli obblighi di pubblicità legale.',
    'privacy.section.controller.title': 'Titolare del Trattamento (Data Controller)',
    'privacy.section.controller.desc': 'Il Titolare del Trattamento è AITHRA S.r.l., con sede legale in Viale Col di Lana 8, 20136 Milano (MI). Richieste inerenti all\'esercizio dei diritti previsti dal Regolamento UE 2016/679 possono essere inoltrate a: info@aithra.it',
    'privacy.section.purposes.title': 'Finalità del Trattamento e Basi Giuridiche',
    'privacy.section.purposes.desc': 'Il trattamento dei dati è finalizzato all\'esecuzione di misure precontrattuali/contrattuali, all\'assolvimento di obblighi fiscali e normativi, e alla gestione delle comunicazioni professionali. La base giuridica risiede nell\'Art. 6.1.b (Esecuzione del contratto) e Art. 6.1.f (Legittimo Interesse) del GDPR.',
    'privacy.section.data.title': 'Natura dei Dati Trattati',
    'privacy.section.data.desc': 'Sono oggetto di trattamento dati tecnici di navigazione (indirizzi IP, metadati di sessione) e dati identificativi forniti esplicitamente dall\'interessato ai fini dell\'instaurazione di rapporti professionali.',
    'privacy.section.rights.title': 'Esercizio dei Diritti dell\'Interessato',
    'privacy.section.rights.desc': 'Ai sensi degli Artt. 15-22 del GDPR, l\'Interessato ha il diritto di accesso, rettifica, cancellazione (oblio), limitazione, portabilità e opposizione al trattamento dei dati personali che lo riguardano.',
    'cookies.banner.text': 'Utilizziamo i cookie per migliorare la tua esperienza sul nostro sito.',
    'cookies.banner.accept': 'Accetta',
    'cookies.banner.decline': 'Rifiuta',
    'cookies.banner.policy': 'Cookie Policy',
    'seo.transparency.title': 'Trasparenza | AITHRA',
    'seo.transparency.description': 'Informazioni societarie e obblighi di trasparenza di AITHRA S.r.l.',
  },
  EN: {
    'nav.projects': 'Projects',
    'nav.services': 'Services',
    'nav.ailab': 'AI.THRA LAB',
    'nav.news': 'Latest News',
    'nav.about': 'About',
    'nav.careers': 'Careers',
    'nav.contact': 'Contact',
    'nav.menu': 'Menu',
    'nav.close': 'Close',
    'footer.transparency': 'TRANSPARENCY OBLIGATIONS',
    'transparency.title': 'TRANSPARENCY OBLIGATIONS',
    'transparency.headline.main': 'TRANSPARENCY',
    'transparency.headline.sub': '& PRIVACY',
    'transparency.desc': 'Regulatory framework and disclosure regarding legal publicity, administrative transparency, and data governance protocols of AITHRA S.r.l.',
    'transparency.section.company.title': 'Corporate & Identification Data',
    'transparency.section.company.name': 'Company Name: AITHRA S.r.l.',
    'transparency.section.company.vat': 'VAT / Tax Code: 14597360966',
    'transparency.section.company.address': 'Registered Office: Viale Col di Lana 8, 20136 Milan (MI)',
    'transparency.section.insurance.title': 'Indemnity & Insurance Coverage',
    'transparency.section.insurance.desc': 'AITHRA S.r.l. operates under a Professional Liability (All Risks) insurance policy, with coverage limits tailored to the complexity of engineering mandates and in full compliance with current regulatory standards for engineering firms.',
    'transparency.section.subsidies.title': 'Transparency Obligations - Public Subsidies',
    'transparency.section.subsidies.desc': 'In accordance with Law 124/2017, please note that State aid and de minimis aid received by the company are recorded in the National Register of State Aid (RNA), fulfilling current legal publicity and transparency requirements.',
    'privacy.section.controller.title': 'Data Controller',
    'privacy.section.controller.desc': 'The Data Controller is AITHRA S.r.l., with registered office at Viale Col di Lana 8, 20136 Milan (MI). Requests regarding the exercise of rights under EU Regulation 2016/679 may be submitted to: info@aithra.it',
    'privacy.section.purposes.title': 'Processing Purposes and Legal Basis',
    'privacy.section.purposes.desc': 'Data processing is strictly aimed at fulfilling pre-contractual/contractual obligations, tax and regulatory compliance, and professional communication management. The legal basis is Art. 6.1.b (Contract execution) and Art. 6.1.f (Legitimate Interest) of the GDPR.',
    'privacy.section.data.title': 'Nature of Processed Data',
    'privacy.section.data.desc': 'Processing concerns technical navigation data (IP addresses, session metadata) and identification data explicitly provided by the data subject for the establishment of professional relationships.',
    'privacy.section.rights.title': 'Data Subject Rights',
    'privacy.section.rights.desc': 'Pursuant to Articles 15-22 of the GDPR, the Data Subject has the right to access, rectification, erasure (oblivion), restriction, portability, and opposition regarding their personal data processing.',
    'cookies.banner.text': 'We use cookies to improve your experience on our site.',
    'cookies.banner.accept': 'Accept',
    'cookies.banner.decline': 'Decline',
    'cookies.banner.policy': 'Cookie Policy',
    'seo.transparency.title': 'Transparency | AITHRA',
    'seo.transparency.description': 'Corporate information and transparency obligations of AITHRA S.r.l.',
    'projects.title': 'SELECTED WORKS',
    'projects.subtitle': 'INTEGRATED EXCELLENCE',
    'projects.selected': 'Portfolio',
    'projects.viewAll': 'View All Projects',
    'project.gardone.title': 'Grand Hotel Gardone',
    'project.gardone.location': 'Gardone Riviera (BS)',
    'project.gardone.category': 'PM & Construction Management',
    'project.gardone.services': 'Project Management, Construction Management',
    'project.gardone.duration': 'December 2025 — Ongoing',
    'project.gardone.value': '€8M (Lots 1 & 2)',
    'project.gardone.desc': 'A visionary transformation for the historical Grand Hotel Gardone, marking the Italian debut of LXR Hotels & Resorts (Hilton). AITHRA coordinates the first and second lots (~10,000 sqm) for Racco Spa, steering the redevelopment towards its 2027 opening.',
    'project.gardone.challenge': 'The complexity lies in balancing the preservation of the architectural heritage with the need for modern high-performance infrastructure. Coordinating large-scale demolitions while simultaneously planning advanced dry construction for luxury hospitality standards requires precise sequencing.',
    'project.gardone.solution': 'As Project and Construction Managers, we implement integrated control systems to monitor every phase of demolition and reconstruction. Our approach ensures that the structural integrity is maintained while the new interior layouts meet modern acoustic and thermal requirements through advanced drywall systems.',
    'project.gardone.outcome': 'The project is currently on track, with the first lots of demolition and interior partitioning progressing according to the technical schedule. We are ensuring a seamless transition from the structural shell to the high-end finishing phases.',
    'project.quilico.title': 'Ex Asilo Quilico & D’andrade Museum',
    'project.quilico.location': 'Pavone Canavese (TO)',
    'project.quilico.category': 'Energy & GSE',
    'project.quilico.services': 'Energy Diagnosis, EGE Services, GSE Management',
    'project.quilico.duration': 'April 2026 — Ongoing',
    'project.quilico.desc': 'A comprehensive energy transition project for the historical Ex Asilo Quilico and D\'andrade Museum. This project exemplifies our ability to integrate regulatory compliance with high-level technical engineering.',
    'project.quilico.challenge': 'Historic buildings often present significant structural constraints for energy upgrades. The goal is to achieve deep retrofitting status while navigating the complex Italian regulatory landscape for historical preservation and public incentives.',
    'project.quilico.solution': 'We deployed certified Energy Management Experts (EGE) to conduct a rigorous pre-intervention diagnosis (UNI CEI EN 16247). This data-driven approach allowed us to select the most efficient technical interventions, which we then translated into a full GSE \'Portaltermico\' management strategy.',
    'project.quilico.outcome': 'By integrating technical diagnosis with administrative strategy, we are securing maximal incentives for the municipality while ensuring a post-intervention energy class jump that significantly reduces operational costs and CO2 footprint.',
    'project.monza.title': 'Cascina San Giuseppe',
    'project.monza.location': 'Monza (MB)',
    'project.monza.category': 'Restoration & Structures',
    'project.monza.services': 'Architecture, Structural Engineering, Safety, Asbestos Management',
    'project.monza.duration': 'April 2026 — Ongoing',
    'project.monza.desc': 'At Cascina San Giuseppe in Monza, AITHRA is managing the restoration of an early 20th-century historical complex, focusing on structural stability and hazardous material remediation.',
    'project.monza.challenge': 'The building suffered from advanced degradation of the wooden roof structures and masonry. The presence of asbestos required a high-standard safety protocol and integrated environmental management.',
    'project.monza.solution': 'We provided a full-cycle engineering service: from 3D survey and feasibility study to the final structural design for roof timber reinforcement and masonry consolidation. Our safety coordination ensures that building residents and workers are protected during the delicate asbestos removal phase.',
    'project.monza.outcome': 'The project preserves the historical character of the facade while delivering a safe, modern roof structure. Our technical-administrative assistance has streamlined the permit process, allowing for an immediate start of works.',
    'project.label.client': 'Client',
    'project.label.area': 'Area',
    'project.label.duration': 'Duration',
    'project.label.value': 'Value',
    'project.heading.challenge': 'The Challenge',
    'project.heading.solution': 'Our Solution',
    'project.heading.outcome': 'The Outcome',
    'project.heading.services': 'Services Provided',
    'project.heading.technical': 'Technical Focus',
    'project.technical.desc': 'Implementing integrated BIM workflows and AI-driven cost control to ensure maximum efficiency in large-scale redevelopments.',
    'project.button.enquire': 'Enquire about a project',
    'project.next': 'NEXT PROJECT',
    'project.viewCase': 'View Full Case Study',
    'project.back': 'BACK',
    'projects.filter.year': 'YEAR',
    'projects.filter.type': 'TYPE',
    'projects.filter.area': 'AREA',
    'projects.filter.country': 'COUNTRY',
    'projects.filter.amount': 'VALUE',
    'projects.filter.services': 'SERVICES',
    'filter.area.range1': '< 500 sqm',
    'filter.area.range2': '500 - 2000 sqm',
    'filter.area.range3': '2000 - 5000 sqm',
    'filter.area.range4': '> 5000 sqm',
    'filter.amount.range1': '< €500k',
    'filter.amount.range2': '€500k - €2M',
    'filter.amount.range3': '€2M - €10M',
    'filter.amount.range4': '> €10M',
    'filter.country.italy': 'Italy',
    'filter.country.usa': 'USA',
    'filter.country.france': 'France',
    'filter.country.germany': 'Germany',
    'filter.country.uk': 'United Kingdom',
    'filter.country.spain': 'Spain',
    'filter.country.switzerland': 'Switzerland',
    'filter.country.uae': 'UAE',
    'filter.all': 'All',
    'filter.type.hospitality': 'Hospitality',
    'filter.type.public': 'Public',
    'filter.type.residential': 'Residential',
    'filter.category.pm': 'PM & Construction Management',
    'filter.category.energy': 'Energy & GSE',
    'filter.category.restoration': 'Restoration & Structures',
    'filter.service.pm': 'Project Management',
    'filter.service.construction': 'Construction Management',
    'filter.service.energy': 'Energy',
    'filter.service.gse': 'GSE',
    'filter.service.architecture': 'Architecture',
    'filter.service.structures': 'Structures',
    'projects.noResults': 'No projects match the selected filters.',
    'ai.tag': 'Innovation Hub',
    'ai.title': 'AI.THRA LAB',
    'ai.desc': 'Artificial intelligence at the service of the project: proprietary algorithms for structural optimization, energy simulation, and generative design.',
    'ai.heads.title': 'HEADS OF THE AREA',
    'ai.heads.01.name': 'CIRIACO ALBERTO BELMONTE',
    'ai.heads.01.role': 'Head of AI',
    'ai.heads.01.bio': 'Leads the strategic vision of the AI Lab, overseeing the development of advanced calculation models and technology integration.',
    'ai.heads.02.name': 'SIMONE MIRAGLIA',
    'ai.heads.02.role': 'AI & BIM Strategy Manager',
    'ai.heads.02.bio': 'Manages the operations of the AI and BIM departments, ensuring a smooth digital transition and workflow optimization.',
    'ai.publications.title': 'PUBLICATIONS',
    'ai.publications.01.title': 'projetando possibilidades conferéncia ubiqua',
    'ai.publications.01.journal': 'SIGRADI 2021 — Strategie Parametriche in un Laboratorio di Progettazione Architettonica, pp 511-522',
    'ai.publications.01.year': '2021',
    'ai.projects.title': 'OUR PROJECTS',
    'ai.projects.01.title': 'ENERGY TWIN 3D',
    'ai.projects.01.type': 'Virtual EGE',
    'ai.projects.01.desc': 'Real-time energy simulations in 3D. An AI trained to interact with the client and optimize global building performance.',
    'ai.projects.01.status': 'In Production',
    'ai.projects.02.title': 'AITHRA OMNIA',
    'ai.projects.02.type': 'Process Bot',
    'ai.projects.02.desc': 'Full infrastructure management: quality control, process tracking, and proactive site support. Estimated error reduction to 3%.',
    'ai.projects.02.status': 'Active Sentinel',
    'ai.projects.03.title': 'URBANISTICA AI',
    'ai.projects.03.type': 'Regulatory Bot',
    'ai.projects.03.desc': 'Real-time regulatory support. Bots trained on Italian urban planning legislation for total compliance in all project phases.',
    'ai.projects.03.status': 'Safe Check',
    'ai.athena.title': 'ATHENA 1',
    'ai.athena.subtitle': 'PROPRIETARY AI ENGINE',
    'ai.athena.desc': 'Our proprietary software for structural optimization and real-time energy simulation.',
    'ai.athena.status': 'SYSTEM STATUS',
    'ai.athena.version': 'VERSION 1.4.2',
    'about.title': 'ABOUT US',
    'about.subtitle': 'EXCELLENCE IN INTEGRATED ENGINEERING',
    'about.desc': 'From over 25 years of combined engineering experience to an innovative AI-driven company. AITHRA brings together a multidisciplinary team of professionals with diverse backgrounds in design, engineering, and technology, united by a shared approach and a common vision.\n\nWe develop integrated solutions where architecture, engineering, and artificial intelligence converge to create buildings capable of managing energy in a predictive, efficient, and adaptive way.\n\nOur work is grounded in experience, but oriented toward innovation: each project is conceived as a system, where technical expertise, process control, and advanced tools operate together to deliver high-performance, resilient, and forward-looking results.',
    'about.headline.main': '25 YEARS OF',
    'about.headline.sub': 'EXCELLENCE',
    'about.philosophy.title': 'OUR EVOLUTION',
    'about.philosophy.text': 'AITHRA was born from the union of twenty-five years of experience in the construction sector with the most advanced Artificial Intelligence technologies.',
    'about.integrated.title': 'MISSION',
    'about.integrated.desc': 'Democratizing innovation to accelerate the energy transition and support ESG criteria.',
    'about.sustainable.title': 'VALUES',
    'about.sustainable.desc': 'Technical excellence, integrated sustainability, and responsible innovation guide our every project.',
    'about.experience.label': 'Experience',
    'about.experience.value': '25+ Years',
    'about.people': 'OUR TEAM',
    'about.people.subtitle': 'BOARD',
    'about.people.desc': 'A team of technicians and researchers dedicated to the digital transformation of the sector.',
    'about.team.fullDesc': 'Our studio is an ecosystem of creativity and collaboration. A space where every team member actively contributes to innovation, working in a dynamic and stimulating environment that promotes well-being and the continuous exchange of knowledge.',
    'about.team.member.01.name': 'Ciriaco Alberto Belmonte',
    'about.team.member.01.role': 'CEO and AI Research Lead',
    'about.team.member.01.degree': 'M.Sc. Civil Engineering (Hydraulics)',
    'about.team.member.02.name': 'Pierluigi Bisogno',
    'about.team.member.02.role': 'Technical Director and Head of Proposal',
    'about.team.member.02.degree': 'M.Sc. Civil Engineering',
    'about.team.member.03.name': 'Francesco Nepita',
    'about.team.member.03.role': 'Production and Construction Manager',
    'about.team.member.03.degree': 'M.Sc. Building Engineering',
    'about.team.employee.01.name': 'Simone Miraglia',
    'about.team.employee.01.role': 'Bid manager and head of Architecture',
    'about.team.employee.01.degree': 'M.Sc. Building Engineering & Architecture',
    'about.team.employee.02.name': 'Daniele Chiriaco',
    'about.team.employee.02.role': 'Project and construction manager',
    'about.team.employee.02.degree': 'M.Sc. Building Engineering',
    'about.team.employee.03.name': 'Brighten Joseph',
    'about.team.employee.03.role': 'MEP & Energy Design Engineer',
    'about.team.employee.03.degree': 'M.Sc. Mechanical Engineering (Control Systems)',
    'about.team.employee.04.name': 'William Koerner',
    'about.team.employee.04.role': 'Senior Architect',
    'about.team.employee.04.degree': 'M.Sc. Environmental Architect',
    'about.presence.title': 'OUR PRESENCE',
    'about.map.title': 'OUR OFFICES',
    'about.map.milan': 'MILAN — VIALE COL DI LANA 8',
    'about.location.01.type': 'Headquarters',
    'about.location.02.type': 'Design Studio',
    'about.location.03.type': 'Innovation Hub',
    'about.location.04.type': 'Regional Office',
    'careers.title': 'CAREERS',
    'careers.subtitle': 'JOIN OUR TEAM',
    'careers.desc': 'We are always looking for talents passionate about innovation and sustainability.',
    'careers.headline.main': 'BUILD',
    'careers.headline.sub': 'YOUR CAREER',
    'careers.job.01.title': 'Administrative Lead',
    'careers.job.01.type': 'Accounting & Invoicing',
    'careers.job.01.desc': 'We are looking for a professional to manage all administrative processes. The candidate will handle accounts payable/receivable, financial flow management on Odoo platform, coordination with accounting consultants, and support in drafting contracts. Excellent knowledge of the English language is required.',
    'careers.job.01.skills': 'Administrative management, basic accounting, personnel administration, fluent English.',
    'careers.job.01.software': 'Odoo ERP, Office Suite (Advanced Excel), e-Invoicing portals.',
    'careers.job.02.title': 'BIM Coordinator',
    'careers.job.02.type': 'Integrated Design',
    'careers.job.02.desc': 'We are selecting a BIM Coordinator with experience in complex multidisciplinary projects. The candidate will be responsible for implementing BIM processes, managing interference (Clash Detection), developing information standards, and optimizing workflows. Excellent knowledge of English is required for coordination with international partners.',
    'careers.job.02.skills': 'BIM Management, Computational Design, Team Coordination, fluent English.',
    'careers.job.02.software': 'Autodesk Revit (Expert), Dynamo, Rhino + Grasshopper, Navisworks, BIM 360/ACC.',
    'careers.job.03.title': 'Junior Architect / Engineer',
    'careers.job.03.type': 'Tender Specialist',
    'careers.job.03.desc': 'The candidate will support the tender office in preparing technical bids for national and international importance. The role involves critical analysis of tender documents, drafting methodological technical reports in Italian and English, and coordinating with joint-venture partners.',
    'careers.job.03.skills': 'Tender analysis, technical writing, professional English, process planning.',
    'careers.job.03.software': 'Office Suite, Adobe Creative Suite (InDesign/Photoshop), Project Management Software.',
    'careers.job.04.title': 'Junior Architect / Engineer',
    'careers.job.04.type': 'Energy Diagnosis specialist',
    'careers.job.04.desc': 'We seek a junior profile focused on energy analysis and sustainability applied to existing buildings. The role involves technical surveys, energy modeling and thermal simulations. Knowledge of English is fundamental for research and development of predictive models with the AI team.',
    'careers.job.04.skills': 'Energy diagnosis, Thermal engineering, Energy modeling, professional English.',
    'careers.job.04.software': 'ACCA Termus, Autodesk Revit, Dynamic simulation software, Excel.',
    'careers.job.05.title': 'Senior MEP Engineer',
    'careers.job.05.type': 'Systems Engineering',
    'careers.job.05.desc': 'We are looking for a MEP Systems Engineer with consolidated experience in the design of complex systems. The candidate must manage projects in total autonomy, from concept to executive phase, ensuring integration with other disciplines and compliance with energy efficiency standards. Fluency in the English language is required.',
    'careers.job.05.skills': 'MEP Design, Management autonomy, Multidisciplinary coordination, fluent English.',
    'careers.job.05.software': 'Autodesk Revit, MagiCAD, Thermal and Electrical calculation software.',
    'careers.apply': 'APPLY NOW',
    'careers.requirements': 'REQUIREMENTS',
    'careers.software': 'REQUIRED SOFTWARE',
    'careers.spontaneous.title': 'SPONTANEOUS APPLICATION',
    'careers.spontaneous.desc': 'Can\'t find the right position? Send us your CV and tell us how you can make a difference.',
    'careers.culture.title': 'MORE THAN A JOB',
    'careers.culture.desc': 'At AITHRA, we don\'t just look for professionals; we look for pragmatic dreamers. We are smart, vibrant people who believe that true innovation comes from the free exchange of ideas. Our environment promotes the cross-contamination of knowledge and ideas: here, every team member is encouraged to challenge the status quo and contribute their unique vision, in a climate of continuous collective growth.',
    'careers.culture.grid.1': 'IDEA CONTAMINATION',
    'careers.culture.grid.2': 'TRANSVERSALITY',
    'careers.culture.grid.3': 'VIBRANT ENVIRONMENT',
    'contact.title': 'CONTACT',
    'contact.subtitle': 'LET\'S TALK ABOUT YOUR PROJECT',
    'contact.desc': 'We are ready to help you realize your most ambitious challenges.',
    'contact.headline.main': 'GET IN',
    'contact.headline.sub': 'TOUCH',
    'contact.details.title': 'DETAILS',
    'contact.details.inquiries': 'INQUIRIES',
    'contact.details.phone': 'PHONE',
    'contact.details.office': 'OFFICE',
    'contact.form.title': 'SEND US A MESSAGE',
    'contact.form.name': 'NAME',
    'contact.form.email': 'EMAIL',
    'contact.form.subject': 'SUBJECT',
    'contact.form.message': 'MESSAGE',
    'contact.form.placeholder.name': 'Your name',
    'contact.form.placeholder.email': 'Your email',
    'contact.form.placeholder.subject': 'What do you want to talk about?',
    'contact.form.placeholder.message': 'Write your message here...',
    'contact.form.send': 'SEND MESSAGE',
    'contact.faq.title': 'FREQUENTLY ASKED QUESTIONS',
    'contact.faq.subtitle': 'Quick answers to the most common questions',
    'contact.faq.01.q': 'How much does an initial consultation cost?',
    'contact.faq.01.a': 'The first introductory consultation is free and without obligation. During the meeting, we analyze your needs and propose a personalized path with a detailed quote.',
    'contact.faq.02.q': 'How quickly will I receive a response?',
    'contact.faq.02.a': 'Our team responds to all requests within 24 business hours. For emergencies, you can contact us directly at the indicated telephone number.',
    'contact.faq.03.q': 'Do you also operate outside Milan?',
    'contact.faq.03.a': 'Yes, we operate throughout the national territory. We have managed projects in Lombardy, Veneto, Emilia-Romagna, Piedmont, and other Italian regions.',
    'contact.faq.04.q': 'Which sectors do you cover?',
    'contact.faq.04.a': 'We work with Public Administrations, industry, tertiary, and residential sectors. We have experience with hospitals, schools, production plants, retail chains, hotels, and condominiums.',
    'contact.faq.05.q': 'Do you also handle incentive procedures?',
    'contact.faq.05.a': 'Absolutely yes. We handle all procedures: White Certificates, Thermal Account 3.0, Transition Plan 5.0, PNRR calls, and regional funds.',
    'home.hero.title': 'Designing a',
    'home.hero.subtitle': 'sustainable and green future',
    'home.hero.tagline': 'AITHRA: FORM. SYSTEM . ENERGY.',
    'home.hero.description': 'We combine architecture, engineering, and process intelligence into a new way of designing.',
    'home.hero.engineering': 'Engineering Excellence',
    'home.integrated.tag': 'Integrated Design',
    'home.approach.tag': 'Our Approach',
    'home.approach.title': 'INTEGRATED DESIGN & TECHNOLOGY',
    'home.approach.desc': 'Our method is based on the fusion of human creativity and parametric precision. Every project is an ecosystem where architecture, engineering, and sustainability coexist in perfect harmony.',
    'home.expertise.tag': 'Our Expertise',
    'home.expertise.title': 'EXCELLENCE IN EVERY DISCIPLINE',
    'home.expertise.desc': 'From integrated design to advanced BIM management, we offer complete solutions for the most ambitious challenges in the construction industry.',
    'home.news.tag': 'News & Insights',
    'home.news.title': 'LATEST NEWS',
    'home.news.item1.title': 'THERMAL ACCOUNT 3.0',
    'home.news.item1.desc': 'Discover new opportunities for energy efficiency and how to access the new 2026 incentives.',
    'home.news.item2.title': 'AI IN DESIGN',
    'home.news.item2.desc': 'How artificial intelligence is revolutionizing building design and sustainability.',
    'home.news.item3.title': 'SMART TOOLS WITH AI',
    'home.news.item3.desc': 'Advanced tools for integrated design and process optimization.',
    'home.news.item4.title': 'ENERGY TRANSITION',
    'home.news.item4.desc': 'Strategies and solutions for a zero-emission future and energy independence.',
    'news.conto-termico.content': `The Thermal Account 3.0, introduced for 2026, represents a milestone in the national strategy for the decarbonization of the building stock. This regulation significantly strengthens incentives for replacing winter air conditioning systems with high-efficiency systems.

Key points of the new regime:
- Higher incentives for air-to-water and geothermal heat pumps, with coverage up to 65% of the costs incurred.
- Inclusion of advanced hybrid systems and integration with solar thermal for domestic hot water production.
- Simplification of access procedures via integrated digital portals, reducing processing times.

The AITHRA team supports clients at every stage: from preliminary energy diagnosis to system design, through to complete management of administrative procedures to ensure maximum return on investment.`,
    'news.ai-engineering.content': `The integration of artificial intelligence into engineering processes is no longer an option, but a necessity to manage the complexity of modern building projects. AITHRA uses proprietary algorithms to transform data into optimized design decisions.

Practical applications:
- Structural Optimization: Reduction of material use (steel and concrete) through generative algorithms that maintain superior safety standards.
- Energy Simulations: Use of predictive models to analyze building behavior in different seasonal climatic conditions.
- Generative Design: Automated exploration of thousands of spatial options to optimize natural light, ventilation, and acoustic comfort.

This approach allows designers and clients to visualize the performance of the work before the construction site even begins, minimizing risks and unforeseen costs.`,
    'news.smart-tools.content': `The new Smart Tools developed by AITHRA are designed to bridge the gap between office design and site execution. Through the use of AI, these tools allow for proactive and intelligent management of all construction phases.

Key features include:
- Real-time Digital Twin: Interactive 3D models that constantaly update reflecting the real progress of the work.
- Automated Quality Control: Computer vision systems that detect discrepancies between the BIM model and the built work, signaling potential clashes.
- Safety Management: Algorithms that monitor the work environment to prevent risk situations for workers.

The adoption of these tools leads to a drastic reduction in material waste and rigorous compliance with established schedules.`,
    'news.energy-transition.content': `The energy transition is the main challenge of our century for the construction sector. New European regulations, including the EPBD (Energy Performance of Buildings Directive) directives, impose increasingly strict standards for energy saving and sustainability.

AITHRA's strategies for the future:
- Building Decarbonization: Replacing fossil sources with renewable energy integrated directly into the architecture.
- Renewable Energy Communities (REC): Designing systems that allow for energy sharing between neighboring buildings, maximizing self-consumption.
- Life Cycle Assessment (LCA): Evaluation of the environmental impact of every building component, from production to disposal.

Investing in sustainability today means not only protecting the planet but also ensuring the real estate value of assets in the long term, anticipating the demands of a market increasingly attentive to ESG criteria.`,
    'news.milan-arch-week.content': `Milan Arch Week is the leading event dedicated to architecture, urban planning, and the future of cities, promoted by the Municipality of Milan, Politecnico di Milano, and Triennale Milano. The event transforms the city into an open-air laboratory to reflect on major contemporary urban transformations.

The management of the event involves choral coordination between academic and cultural institutions, proposing a program that ranges from lectures by internationally renowned architects to operational workshops, guided tours, and debates open to the public.

The focus of the 2026 edition centers on the "Next City," analyzing how technology, urban greenery, and new forms of mobility can integrate to create more resilient and inclusive citizen ecosystems.`,
    'news.aithra-genesis.content': `The name AITHRA derives from the Greek term αἰθήρ (aithḗr), which identifies the ether: the purest air, the clear sky, what is invisible but essential. A concept that recalls transparency, lightness, and energy, and that consistently represents the role that intelligent technologies can take on today in complex processes.

AITHRA is an innovative start-up that develops integrated solutions between design, engineering, and artificial intelligence, with the goal of making systems more efficient, controllable, and sustainable. Innovation is not treated as a separate element, but as a structural part of the method, capable of operating discreetly yet decisively within processes.

The company was born from the meeting of professionals who share a common path and over twenty-five years of collective experience in the sector. A group that chose to combine complementary skills—design, technical, and organizational—to build a more integrated operating model.

AITHRA positions itself as a single point of contact for public and private clients, accompanying every intervention throughout all its phases: from preliminary analysis to design, from coordination to implementation. An approach that allows for continuity, control, and consistency throughout the entire project development.

At the core is a clear vision: to structure a process in which different skills dialogue in a systemic way, supported by advanced tools and an organization capable of governing complexity without losing it.

AITHRA is, therefore, a system built to give shape to more conscious projects, in which technology, method, and design operate together with precision and continuity.`,
    'news.archive.title': 'NEWS & PUBLICATIONS ARCHIVE',
    'news.archive.subtitle': 'STORIES, PROJECTS AND INTERVENTIONS',
    'news.filter.all': 'ALL',
    'news.filter.articles': 'ARTICLES',
    'news.filter.publications': 'PUBLICATIONS',
    'news.filter.events': 'EVENTS',
    'news.filter.stories': 'STORIES',
    'services.title': 'OUR SERVICES',
    'services.subtitle': 'INTEGRATED SOLUTIONS FOR THE FUTURE OF CONSTRUCTION',
    'services.architettura.title': 'ARCHITECTURE',
    'services.architettura.desc': 'Integrated architectural design in a BIM environment. We transform visions into reality through functional, aesthetic, and sustainable design.',
    'services.architettura.items': 'Concept Design, Final and Executive Design, Advanced BIM Modeling, Interior Design, LEED/BREEAM Certifications',
    'services.strutture.title': 'STRUCTURES',
    'services.strutture.desc': 'Cutting-edge engineering solutions for complex structures. Safety, material optimization, and technical precision.',
    'services.strutture.items': 'NTC 2018 Structural Calculation, Anti-seismic Design, Building Consolidation, Steel and Reinforced Concrete Structures, FEM Analysis',
    'services.impianti.title': 'SYSTEMS & MEP',
    'services.impianti.desc': 'Design of high-efficiency plant systems. Perfect integration between architecture and technology for maximum comfort.',
    'services.impianti.items': 'Thermal and Electrical Systems, Photovoltaic and Renewables, Building Automation (BACS), HVAC Systems, Fire Protection',
    'services.ai.title': 'AI & DIGITAL TWIN',
    'services.ai.title2': 'DIGITAL TWIN',
    'services.ai.desc': 'Development of digital models and predictive algorithms for the optimization of energy and management performance.',
    'services.ai.items': 'Proprietary Predictive Algorithms, Energy Digital Twins, AITHRA SaaS Platform, IoT/BMS Integration',
    'services.energia.title': 'SUSTAINABILITY & ENERGY',
    'services.energia.desc': 'Strategic consulting for the energy transition. Diagnosis, monitoring, and access to incentives for a Green future.',
    'services.energia.items': 'D.Lgs 102/2014 Energy Audits, ESG Consulting, 2026 Incentives Access, Energy Communities (CER)',
    'services.cta.title': 'Our multidisciplinary approach redefines the boundaries of engineering.',
    'services.cta.tagline': 'Integrated Design — AI Optimization — Sustainable Future',
    'services.cta.button': 'Work with us',
    'services.tender.title': 'TENDER',
    'services.tender.desc': 'Technical and management support for public and private tenders. Complete technical documentation management.',
    'services.tender.items': 'Public Procurement Management, PNRR, Bill of Quantities, Technical Tender Support',
    'services.rilievo.title': 'SURVEY & DIGITALIZATION',
    'services.rilievo.desc': 'Digital acquisition of as-built status through advanced survey technologies and millimeter precision.',
    'services.rilievo.items': '3D Laser Scanner Surveys, Photogrammetry, BIM Restitution (Scan-to-BIM), Architectural Surveys',
    'footer.desc': 'AITHRA is a leading engineering and architecture firm, specializing in integrated and sustainable solutions.',
    'footer.navigation': 'NAVIGATION',
    'footer.contact': 'CONTACT',
    'footer.newsletter': 'NEWSLETTER',
    'footer.newsletter.desc': 'Subscribe to receive updates on our projects and technological innovations.',
    'footer.join': 'JOIN',
    'footer.allRights': '© 2026 AITHRA S.R.L. ALL RIGHTS RESERVED.',
    'footer.privacy': 'PRIVACY POLICY',
    'footer.terms': 'TERMS & CONDITIONS',
    'home.hero.intro.desc': 'We bridge the gap between human creativity and computational precision. AITHRA provides integrated solutions in architecture, structural engineering, MEP, BIM, and sustainability, powered by our proprietary EGE Virtuale software, with over twenty-five years of experience in the sector.',
    'home.hero.intro.expertise': 'Expertise',
    'home.hero.intro.integrated': 'Integrated Design & BIM',
    'home.hero.intro.sustainability': 'Energy Sustainability',
    'home.hero.intro.construction': 'Site Management',
    'home.integrated.title': 'INTEGRATED DESIGN',
    'home.integrated.title.sub': 'INTEGRATED ENGINEERING',
    'home.integrated.quote': 'We provide a seamless integration of disciplines, ensuring that every project is optimized for performance, sustainability, and human experience.',
    'home.integrated.desc': 'Our holistic approach ensures that architecture, engineering, and environmental strategy work as a single, high-performance organism.',
    'home.integrated.link': 'Explore our services —>',
    'home.approach.step1.title': 'RESEARCH',
    'home.approach.step1.desc': 'Deep analysis of context and constraints.',
    'home.approach.step2.title': 'OPTIMIZATION',
    'home.approach.step2.desc': 'Algorithmic refinement of every parameter.',
    'home.approach.step3.title': 'PRECISE DELIVERY',
    'home.approach.step3.desc': 'Meticulous execution through BIM and smart process management.',
    'home.expertise.core.title': 'Core Focus',
    'home.expertise.core.item1': 'Multidisciplinary Design',
    'home.expertise.core.item2': 'Energy Sustainability',
    'home.expertise.core.item3': 'Parametric Architecture',
    'home.expertise.digital.title': 'Digital Twin',
    'home.expertise.digital.item1': 'BIM LOD 500',
    'home.expertise.digital.item2': 'Smart Asset Management',
    'home.expertise.digital.item3': 'Predictive Maintenance',
    'home.news.more': 'Read More —>',
    'home.metric.title.1': 'We operate at the',
    'home.metric.title.2': 'intersection',
    'home.metric.title.3': 'of intuition and',
    'home.metric.title.4': 'parametric precision.',
    'home.metric.desc': 'AITHRA is not just an engineering firm. We are a laboratory of the built environment, where every structure is optimized through proprietary AI models to achieve unprecedented levels of efficiency and aesthetic harmony.',
    'home.metric.label': 'Core Metric',
    'home.metric.value.desc': 'Average reduction in structural carbon footprint across all 2026 projects.',
    'home.team.desc': 'Our team is a hybrid of engineering excellence and computational research.',
    'home.cta.title.1': 'Let\'s build the',
    'home.cta.title.2': 'future together.',
    'home.cta.button': 'Start a Conversation',
    'seo.home.title': 'AITHRA | Integrated Engineering, Architecture and AI',
    'seo.home.description': 'AITHRA combines architecture, engineering, and artificial intelligence to design a sustainable future. Over 25 years of experience in integrated engineering solutions.',
    'seo.projects.title': 'Projects | Engineering and Architecture Portfolio | AITHRA',
    'seo.projects.description': 'Explore AITHRA\'s selected works: from Grand Hotel Gardone to the energy redevelopment of the D’andrade Museum. Excellence in PM and Construction Management.',
    'seo.services.title': 'Services | Engineering, Architecture and Sustainability | AITHRA',
    'seo.services.description': 'Integrated solutions: BIM Architecture, Structural Calculation, MEP Systems, Digital Twin, and Energy Transition consulting.',
    'seo.ailab.title': 'AI.THRA LAB | Innovation and Artificial Intelligence | AITHRA',
    'seo.ailab.description': 'Our Innovation Hub: proprietary algorithms for structural optimization, energy simulation, and generative design applied to the building industry.',
    'seo.about.title': 'About Us | Our Evolution and Team | AITHRA',
    'seo.about.description': 'Discover AITHRA\'s history, mission, and the multidisciplinary team led by CEO Ciriaco Alberto Belmonte. Technical tradition and technological innovation.',
    'seo.careers.title': 'Careers | Join the AITHRA Team | Work with Us',
    'seo.careers.description': 'We are looking for talent: BIM Coordinators, MEP Engineers, Energy Diagnosis specialists. Join a vibrant and innovative environment.',
    'seo.news.title': 'News and Publications | Insights from AITHRA World',
    'seo.news.description': 'Stay updated on Thermal Account 3.0, AI in design, and the latest news on energy transition and sustainability.',
    'seo.contact.title': 'Contact | Let’s Talk About Your Project | AITHRA',
    'seo.contact.description': 'Contact the AITHRA studio in Milan. Request a consultation for integrated engineering, GSE procedures, or sustainable design.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('IT');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
